on:
  issues:
  issue_comment:
  push:
    branches: [develop]
jobs:
  readme-writer:
    name: Write README.md
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: develop
    - name: Set up python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: '3.9'
    - run: |
        pip install -r scripts/readme-writer/requirements.txt
        python scripts/readme-writer/readme_writer.py
        cat README.md
    - name: Commit README.md
      uses: stefanzweifel/git-auto-commit-action@v4
      env:
        # we use a personal access token of openfoodfacts-bot to allow bypassing branch protection rules
        GITHUB_TOKEN: "${{ secrets.README_WRITER_PAT }}"
      with:
        branch: develop
        repository: .
        file_pattern: README.md
        commit_message: Update README.md
        commit_options: '--no-verify --signoff'
