on:
  issues:
  issue_comment:
  pull_request:

jobs:
  readme-writer:
    name: Write README.md
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      ref: master
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: |
        pip install -r scripts/readme-writer/requirements.txt
        python scripts/readme-writer/readme_writer.py
        cat README.md
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: Commit README.md
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: master
        repository: .
        file_pattern: README.md
        commit_message: Update README.md
        commit_options: '--no-verify --signoff'
