on:
  issues:
  issue_comment:
  push:
    branches: [readme-writer]
jobs:
  readme-writer:
    name: Write README.md
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: develop
        # we use a personal access token of openfoodfacts-bot to allow bypassing branch protection rules
        token: "${{ secrets.README_WRITER_PAT }}"
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - run: |
        pip install -r scripts/readme-writer/requirements.txt
        python scripts/readme-writer/readme_writer.py
        cat docs/virtual-machines.md
    - name: Commit docs/virtual-machines.md.md
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: develop
        repository: .
        file_pattern: docs/virtual-machines.md
        commit_message: Update docs/virtual-machines.md
        commit_options: '--no-verify --signoff'
